### ISSUE TITLE
Append route parameters to command parameters

### ISSUE THREAD

**Issue by eps90** [eps90/req2cmd-bundle#6]
Currently, only request body is deserialized. Allow appending route parameters to the body.
For example, given a route:

```yml
app.add_post:
  path: /update-post-title/{id}.{_format}
  defaults:
    _command_class: AppBundle\Command\UpdatePostTitle
```
and request:
```
PUT http://example.com/update-post-title/3.json
```

with requested body:
```json
{
    "title": "My updated article"
}
```

this command's constructor should work:

```php
<?php

// ...
final class UpdatePostTitle
{
    // ...
    public static function fromArray(array $commandProps): self
    {
        return new self($commandProps['id'], $commandProps['title']);
    }
}
```
